### ISSUE TITLE
invalid file capture length 134217728, bigger than maximum of 262144

### ISSUE THREAD

**Issue by alkino** [wjt/bustle#4]
Hi,
Running bustle from master (b6780984b92400cbce8db3df57f3d0d872ed377a), and trying to open a pcap generated by bustle-pcap 0.6.2 and libpcap on 1.8.1.
I got this error:
    invalid file capture length 134217728, bigger than maximum of 262144

I read here and there some things about pcap, bustle, but I cannot figure out what I'm supposed to do to make it works.

Can we have some help on that?

Regards,
alkino

**Comment by wjt** [comment]
Ask your distro to cherry-pick the two libpcap patches linked [here](https://github.com/wjt/bustle/commit/f62cf6bfa662af4ae39effbbd4891bc619e3b4e9). Or, install Bustle from [Flathub](https://flathub.org/) which bundles the fix.

**Comment by alkino** [comment]
Thanks ;)
