### ISSUE TITLE
Pattern match failure

### ISSUE THREAD

**Issue by jtojnar** [wjt/bustle#5]
Running 0.6.2, when I stop the capture I get the following error:

![screenshot from 2017-12-16 06-57-23](https://user-images.githubusercontent.com/705123/34067737-660207aa-e22e-11e7-8918-481e8846206e.png)

When I click the save button, the application crashes with the following message in the console:

```
bustle: user error (Pattern match failure in do expression at Bustle/UI.hs:273:5-35)
```

Might be also the cause of insensitive PDF export and the menu items.

**Comment by wjt** [comment]
This is a libpcap bug. See  #4 for suggested fixes.

**Comment by jtojnar** [comment]
Thanks, that fixed all the issues. Sorry, I missed that.
